---

- name: Create unix group {{ unix_group.key }} with random gid
  group:
    name: "{{ unix_group.key }}"
    state: "{{ unix_group.value.state | default('present') }}"
  when: unix_group.value.gid is not defined or unix_group.value.gid is defined and unix_group.value.gid == ""

- name: Create unix group {{ unix_group.key }} with pre-defined gid
  group:
    name: "{{ unix_group.key }}"
    gid: "{{ unix_group.value.gid }}"
    state: "{{ unix_group.value.state | default('present') }}"
  when: unix_group.value.gid is defined and unix_group.value.gid != ""