name: Ansible Linter

on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]

jobs:
  ansible-lint:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Run ansible-lint
      uses: ansible/ansible-lint@262624cd0ab22a4221293216856c59671ce7aa5e # v26.6.0
      with:
        args: "--config-file .ansible-lint"
        setup_python: "true"
