name: Release to Ansible Galaxy

on:
  push:
    tags:
    - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ansible Galaxy
      run: |
        apt update --yes
        apt install --yes ansible
    - env:
        ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
      name: Update Ansible Galaxy
      run: |
        ansible-galaxy role import --token=${ANSIBLE_GALAXY_TOKEN} volker-raschek ansible-role-unix-users