---

unix_groups: {}
#   alice:
#     gid: 1001
#     state: present
#   bob:
#     gid: 1001
#     state: absent

unix_users: {}
#   alice:
#     state: "present"
#     name: "Alice"
#     uid: "1000"
#     ssh:
#       config:
#       - Host: "*"
#         StrictHostKeyChecking: "no"
#         UserKnownHostFile: /dev/null
#       authorized_keys:
#       - alice@alice-pc.pub
#       private_keys:
#       - alice@alice-pc.ed25519.key
#     home: /home/alice
#     btrfs: false
#     shell: /bin/bash
#     group: alice
#     groups: []
#     password: ""
#     email: alice@example.local
